name: Build metoer app
on: [push]
jobs:
  Building-Meteor-App:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '2.10.0'
      - run: meteor npm install
      # - run: meteor npm test
      - run: meteor build
