name: Build metoer app
on: [push]
jobs:
  Building-Meteor-App:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '1.8.1'
      - run: meteor npm install
      - run: meteor npm test
      - run: meteor build
